// Generated by scripts/generate-operator-contract.mjs
export type HypotheticalChange = {
  kind: "CI_PASSED" | "DEADLINE_SHIFT_MINUTES" | "RESOURCE_AVAILABLE_AT";
  target: string;
  value: string;
};
export type OperatorAgentTrace = {
  agent_id: "operator_intent_interpreter" | "simulation_agent";
  attempts: number;
  input_tokens: number;
  latency_ms: number;
  model: string;
  output_tokens: number;
  request_id: string;
  total_tokens: number;
  validation?: "PASSED";
};
export type OperatorEvidence = {
  evidence_id: string;
  observed_at: string | null;
  title: string;
};
export type OperatorFact = {
  evidence_ids: string[];
  fact_id: string;
  text: string;
};
export type OperatorIntent = {
  clarification?: string | null;
  constraints: string[];
  disposition: "SUPPORTED" | "CLARIFICATION_REQUIRED" | "UNSUPPORTED";
  fact_ids: string[];
  hypothetical_changes: HypotheticalChange[];
  incident_id: string;
  intent_type?: "INSPECT" | "EXPLAIN" | "SIMULATE" | null;
  question: string;
  recovery_attempt?: number | null;
  subject: "OBJECTIVE" | "RECOVERY" | "CALENDAR" | "EVIDENCE" | "CHRONOLOGY";
};
export type OperatorQuery = { incident_id: string; message: string };
export type OperatorResponse = {
  agents: OperatorAgentTrace[];
  answer: string;
  disposition: "SUPPORTED" | "CLARIFICATION_REQUIRED" | "UNSUPPORTED";
  evidence: OperatorEvidence[];
  external_effects_executed?: false;
  facts: OperatorFact[];
  generated_at: string;
  hypothetical_deadline?: string | null;
  incident_id: string;
  intent: OperatorIntent;
  provenance: "AUTHORITATIVE_SNAPSHOT" | "HYPOTHETICAL_NO_ACTION";
  request_id: string;
  revision: number;
  simulation?: SimulationResult | null;
  snapshot_fingerprint: string;
};
export type SimulationFuture = {
  consequence: string;
  required_verification: string[];
  title: string;
  tradeoffs: string[];
};
export type SimulationResult = {
  assumptions: string[];
  candidate_futures: SimulationFuture[];
  evidence_ids: string[];
  external_effects_executed: boolean;
  likely_objective_outcome:
    "MAY_IMPROVE" | "STILL_AT_RISK" | "INSUFFICIENT_EVIDENCE";
  provenance: "HYPOTHETICAL_NO_ACTION";
  risk_critique: string[];
  scenario_summary: string;
  threatened_invariants: string[];
  unsupported_assumptions: string[];
};
