import { Canvas, useFrame, useLoader, useThree } from "@react-three/fiber";
import { Suspense, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

type Profile="reference"|"production";
type StoryScale="hero"|"impact"|"futures"|"action";
type Metrics={calls:number;triangles:number;materials:number;average:number;p95:number};
const URLS={reference:"/experiments/production-presentation-v1/reflow-orb-reference-master.glb",production:"/experiments/production-presentation-v1/reflow-orb-production-presentation-v1.glb"};
const CONTEXT={website:"#f6f3ea",elevated:"#fbf9f3",high:"#fffdf9"};
const PLACEMENT:Record<StoryScale,{scale:number;x:number,y:number}>={hero:{scale:1.0,x:0,y:0},impact:{scale:.82,x:.65,y:.15},futures:{scale:.65,x:0,y:.45},action:{scale:.67,x:-2.05,y:.55}};

function CameraAim(){const camera=useThree(s=>s.camera);useLayoutEffect(()=>{camera.lookAt(0,.20,0);camera.updateProjectionMatrix()},[camera]);return null}
function Environment({profile}:{profile:Profile}){const{gl,scene}=useThree();useEffect(()=>{const gen=new THREE.PMREMGenerator(gl);const room=new RoomEnvironment();const tex=gen.fromScene(room,.04).texture;scene.environment=tex;scene.environmentIntensity=profile==="production"?.30:.26;return()=>{scene.environment=null;tex.dispose();room.dispose();gen.dispose()}},[gl,scene,profile]);return null}
function Model({profile}:{profile:Profile}){const gltf=useLoader(GLTFLoader,URLS[profile]);const model=useMemo(()=>gltf.scene.clone(true),[gltf.scene]);useLayoutEffect(()=>model.traverse(n=>{if(n instanceof THREE.Mesh){n.castShadow=true;n.receiveShadow=true}}),[model]);return <primitive object={model}/>}

function BroadShadow(){const map=useMemo(()=>{const c=document.createElement("canvas");c.width=c.height=256;const x=c.getContext("2d")!;const g=x.createRadialGradient(128,128,12,128,128,126);g.addColorStop(0,"rgba(30,42,34,.20)");g.addColorStop(.38,"rgba(30,42,34,.09)");g.addColorStop(1,"rgba(30,42,34,0)");x.fillStyle=g;x.fillRect(0,0,256,256);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t},[]);useEffect(()=>()=>map.dispose(),[map]);return <mesh position={[.1,-.172,.30]} rotation-x={-Math.PI/2}><planeGeometry args={[7.1,4.6]}/><meshBasicMaterial map={map} transparent opacity={.09} depthWrite={false}/></mesh>}
function Satellites({profile}:{profile:Profile}){const color=profile==="production"?"#9ead99":"#aeb7a7";const items:[[number,number,number],number,[number,number,number]][]=[[[-3.4,.02,-.92],.205,[1,.96,1.05]],[[-3.26,.02,1.76],.22,[1.02,.97,1]],[[3.42,.02,-.88],.215,[1.04,.97,1.02]]];return <>{items.map(([p,r,s],i)=><mesh key={i} position={p} scale={s} castShadow><icosahedronGeometry args={[r,5]}/><meshPhysicalMaterial color={color} roughness={profile==="production"?.64:.72} clearcoat={.03}/></mesh>)}</>}
function Probe({onMetrics}:{onMetrics:(m:Metrics)=>void}){const gl=useThree(s=>s.gl),scene=useThree(s=>s.scene),samples=useRef<number[]>([]);useFrame((_,d)=>{samples.current.push(d*1000);if(samples.current.length>180)samples.current.shift();if(samples.current.length===180){const sorted=[...samples.current].sort((a,b)=>a-b),mats=new Set<THREE.Material>();scene.traverse(n=>{if(n instanceof THREE.Mesh)(Array.isArray(n.material)?n.material:[n.material]).forEach(m=>mats.add(m))});onMetrics({calls:gl.info.render.calls,triangles:gl.info.render.triangles,materials:mats.size,average:+(sorted.reduce((a,b)=>a+b,0)/sorted.length).toFixed(2),p95:+sorted[Math.floor(sorted.length*.95)].toFixed(2)})}});return null}

function PresentationCanvas({profile,scale,bg,onMetrics}:{profile:Profile;scale:StoryScale;bg:keyof typeof CONTEXT;onMetrics:(m:Metrics)=>void}){const p=PLACEMENT[scale];return <Canvas className="presentation-canvas" dpr={[1,1.5]} shadows camera={{position:[0,6.55,9.75],fov:24,near:.1,far:80}} gl={{antialias:true,alpha:false,powerPreference:"high-performance"}}><color attach="background" args={[CONTEXT[bg]]}/><CameraAim/><Environment profile={profile}/><hemisphereLight args={["#fffaf1","#abb9ad",profile==="production"?1.38:1.24]}/><spotLight castShadow position={[-4.7,8.2,5.2]} intensity={profile==="production"?74:68} distance={30} angle={.72} penumbra={.98} color="#fff1df" shadow-mapSize={[2048,2048]}/><directionalLight position={[5,3.3,-3]} intensity={profile==="production"?.80:.60} color="#dce8dd"/><directionalLight position={[-4,2,-4]} intensity={profile==="production"?.34:.22} color="#f0d9bc"/><Suspense fallback={null}><group position={[p.x,p.y,0]} scale={p.scale}><Model profile={profile}/><Satellites profile={profile}/></group></Suspense><mesh position-y={-.18} rotation-x={-Math.PI/2} receiveShadow><planeGeometry args={[24,24]}/><shadowMaterial transparent opacity={profile==="production"?.075:.055} color="#2d382f"/></mesh>{profile==="production"&&<BroadShadow/>}<Probe onMetrics={onMetrics}/></Canvas>}

export function ProductionPresentationLab(){const q=new URLSearchParams(location.search);const profile=(q.get("profile")??"production") as Profile|"split";const scale=(q.get("scale")??"hero") as StoryScale;const bg=(q.get("bg")??"website") as keyof typeof CONTEXT;const hide=q.get("ui")==="0";const[metrics,setMetrics]=useState<Metrics|null>(null);const canvas=(p:Profile)=><PresentationCanvas profile={p} scale={scale} bg={bg} onMetrics={setMetrics}/>;return <main className={`presentation-lab ${hide?"hide-ui":""}`}>{!hide&&<header><p>Phase 3.6D · isolated presentation calibration</p><h1>Reference master / production profile</h1><nav><a href="?lab=presentation&profile=reference">Reference</a><a href="?lab=presentation&profile=production">Production</a><a href="?lab=presentation&profile=split">50/50</a></nav></header>}{profile==="split"?<section className="presentation-split"><figure>{canvas("reference")}<figcaption>Reference master</figcaption></figure><figure>{canvas("production")}<figcaption>Production presentation</figcaption></figure></section>:<section className="presentation-stage">{canvas(profile)}</section>}{!hide&&metrics&&<aside className="presentation-metrics">{metrics.calls} calls · {metrics.triangles.toLocaleString()} triangles · {metrics.materials} materials · {metrics.average} ms avg · {metrics.p95} ms p95</aside>}</main>}

useLoader.preload(GLTFLoader,URLS.reference);useLoader.preload(GLTFLoader,URLS.production);
